fix macos pre-HighSierra upload to git from travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,63 +31,50 @@ env:
   - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --disable-tests" CPPFLAGS="-DDEBUG_LOCKORDER -DENABLE_DASH_DEBUG" PYZMQ=true 
   - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" OSX_SDK=10.11 GOAL="deploy"
 before_install:
-- travis_retry sudo apt-get install python-dev
-- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
-  sed "s|::|:|g")
+  - travis_retry sudo apt-get install python-dev
+  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
 install:
-- if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
-- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+  - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
+  - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
+  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
 before_script:
-- unset CC; unset CXX
-- mkdir -p depends/SDKs depends/sdk-sources
-- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz ]; then
-  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.xz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz;
-  fi
-- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz ]; then
-  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz; fi
-- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+  - unset CC; unset CXX
+  - mkdir -p depends/SDKs depends/sdk-sources
+  - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.xz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz; fi
+  - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.xz; fi
+  - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
 script:
-- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
+  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
 #- contrib/devtools/git-subtree-check.sh src/univalue
 #- contrib/devtools/git-subtree-check.sh src/secp256k1
 #- contrib/devtools/check-doc.py
 #- contrib/devtools/logprint-scanner.py
-- if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then contrib/devtools/lint-whitespace.sh;
-  fi
-- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --disable-tests --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
-  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-- "./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (cat
-  config.log && false)"
-- make distdir PACKAGE=aprcoin VERSION=$HOST
-- cd aprcoin-$HOST
-- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
-  ( cat config.log && false)"
-- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
-  V=1 ; false )
-- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-- if [ "$RUN_TESTS" = "true" -a "$WINE" != "true" ]; then make $MAKEJOBS check VERBOSE=1;
-  fi
-- if [ "$RUN_TESTS" = "true" -a "$WINE" = "true" ]; then wine src/test/test_aprcoin.exe;
-  fi
-- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
+  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then contrib/devtools/lint-whitespace.sh; fi
+  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+  - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --disable-tests --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+  - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
+  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
+  - "./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (cat config.log && false)"
+  - make distdir PACKAGE=aprcoin VERSION=$HOST
+  - cd aprcoin-$HOST
+  - "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)"
+  - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
+  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
+  - if [ "$RUN_TESTS" = "true" -a "$WINE" != "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
+  - if [ "$RUN_TESTS" = "true" -a "$WINE" = "true" ]; then wine src/test/test_aprcoin.exe; fi
+  - if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
 after_script:
-- echo $TRAVIS_COMMIT_RANGE
-- echo $TRAVIS_COMMIT_LOG
+  - echo $TRAVIS_COMMIT_RANGE
+  - echo $TRAVIS_COMMIT_LOG
 before_deploy:
-- if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv Aprcoin-Core.dmg Aprcoin-Core-$TAG-macosx-generic.dmg;
-  FILE=Aprcoin-Core-$TAG-macosx-generic.dmg; else HERE=$(pwd); cd $OUTDIR; zip -r
-  $HERE/$HOST.zip bin/; cd $HERE; FILE="$HOST.zip"; fi
-- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
+  - if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv Aprcoin-Core.dmg Aprcoin-Core-$TAG-macosx-generic.dmg; FILE=Aprcoin-Core-$TAG-macosx-generic.dmg; else HERE=$(pwd); cd $OUTDIR; zip -r $HERE/apr-$TAG-$HOST.zip bin/; cd $HERE; FILE="dev-$TAG-$HOST.zip"; fi
+  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
 deploy:
   provider: releases
   api_key:
     secure: x3lDl+XzNnDYK89PA4nGPtLaVPfXUCFYjFM0flAtK+dGCF9ROOIw72MF1tyMj9il+pf0Y5ydCgcZlbO25SylY5VHoXzV9lJxwKw89VoqsQ9HwiF4E5s6ZFyOyTAlY3sNNWNJSwckKRl0bVEqkMCOqo20ZvmQEAwiPhpPURCxXpN2fR4YF/H0Rv3nK2SsI4U4GFcYoW+Wcvn7i2pfQziVey+b2UsRGR40NyS1vK+3vmd3oeTQQtEnrlYVHL/JsljSqensygMnBMmyO8ZPqfA46hyoF4/sxpbmvUm/GDRRh2/07AUFTO4agsmEl000BxtAL9RiXwJCcEZA9iMl5VRRw/WjI1/795yhLm87v04ci7cLXwSEcxphA7dgqqF+VJXcqfCA/nZH4SirG4uJ2PyI6v8KdO4pjR7RTvBsVlm5dXCq/pxqo5vSB0903COJzphnZnPGkbs99usxpRwnSf1D9nX9qCwpAmZ1EpIOn826/ooSIyOwEFTCtuK/nUTm/Ndb44MQnERSOjq3zLGDJncW+Gv2t8ErwP4iQ+ZCJbSihtBD9hitGQtuPCBAqehWMsbFdOV8BosthZpE0n7D97qIkd6TcHxL5Is/Mf0ABzxfCktSq6dqhfIlE5c3fiNez0aMw1ApEUpspMQ3S5HTnY+loib1YxC+P7l9563uR6f/r6g=
-  file: "$HOST.zip"
+  file: "$FILE"
   on:
     repo: ScaMar/zenith-repository
     branch: master
